{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 18,
   "id": "3e94a9d1-1098-4fa8-a86b-2bae9aeac9d4",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: cocoex in /opt/conda/lib/python3.10/site-packages/cocoex-0.0.0-py3.10-linux-x86_64.egg (0.0.0)\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    }
   ],
   "source": [
    "pip install cocoex"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "id": "2d3c1dbf-a63d-4738-8ada-164ca1bbc0ff",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting xgboost\n",
      "  Using cached xgboost-2.0.3-py3-none-manylinux2014_x86_64.whl.metadata (2.0 kB)\n",
      "Requirement already satisfied: numpy in /opt/conda/lib/python3.10/site-packages (from xgboost) (1.24.4)\n",
      "Requirement already satisfied: scipy in /opt/conda/lib/python3.10/site-packages (from xgboost) (1.10.1)\n",
      "Using cached xgboost-2.0.3-py3-none-manylinux2014_x86_64.whl (297.1 MB)\n",
      "Installing collected packages: xgboost\n",
      "Successfully installed xgboost-2.0.3\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    }
   ],
   "source": [
    "pip install xgboost"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "id": "df88ce56-8a4a-48d1-a671-f7b9bcaf4350",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting sklearn\n",
      "  Using cached sklearn-0.0.post12.tar.gz (2.6 kB)\n",
      "  Preparing metadata (setup.py) ... \u001b[?25lerror\n",
      "  \u001b[1;31merror\u001b[0m: \u001b[1msubprocess-exited-with-error\u001b[0m\n",
      "  \n",
      "  \u001b[31m×\u001b[0m \u001b[32mpython setup.py egg_info\u001b[0m did not run successfully.\n",
      "  \u001b[31m│\u001b[0m exit code: \u001b[1;36m1\u001b[0m\n",
      "  \u001b[31m╰─>\u001b[0m \u001b[31m[15 lines of output]\u001b[0m\n",
      "  \u001b[31m   \u001b[0m The 'sklearn' PyPI package is deprecated, use 'scikit-learn'\n",
      "  \u001b[31m   \u001b[0m rather than 'sklearn' for pip commands.\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m Here is how to fix this error in the main use cases:\n",
      "  \u001b[31m   \u001b[0m - use 'pip install scikit-learn' rather than 'pip install sklearn'\n",
      "  \u001b[31m   \u001b[0m - replace 'sklearn' by 'scikit-learn' in your pip requirements files\n",
      "  \u001b[31m   \u001b[0m   (requirements.txt, setup.py, setup.cfg, Pipfile, etc ...)\n",
      "  \u001b[31m   \u001b[0m - if the 'sklearn' package is used by one of your dependencies,\n",
      "  \u001b[31m   \u001b[0m   it would be great if you take some time to track which package uses\n",
      "  \u001b[31m   \u001b[0m   'sklearn' instead of 'scikit-learn' and report it to their issue tracker\n",
      "  \u001b[31m   \u001b[0m - as a last resort, set the environment variable\n",
      "  \u001b[31m   \u001b[0m   SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL=True to avoid this error\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m More information is available at\n",
      "  \u001b[31m   \u001b[0m https://github.com/scikit-learn/sklearn-pypi-package\n",
      "  \u001b[31m   \u001b[0m \u001b[31m[end of output]\u001b[0m\n",
      "  \n",
      "  \u001b[1;35mnote\u001b[0m: This error originates from a subprocess, and is likely not a problem with pip.\n",
      "\u001b[1;31merror\u001b[0m: \u001b[1mmetadata-generation-failed\u001b[0m\n",
      "\n",
      "\u001b[31m×\u001b[0m Encountered error while generating package metadata.\n",
      "\u001b[31m╰─>\u001b[0m See above for output.\n",
      "\n",
      "\u001b[1;35mnote\u001b[0m: This is an issue with the package mentioned above, not pip.\n",
      "\u001b[1;36mhint\u001b[0m: See above for details.\n",
      "\u001b[?25hNote: you may need to restart the kernel to use updated packages.\n"
     ]
    }
   ],
   "source": [
    "pip install sklearn"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 50,
   "id": "f8bf82e3-c119-46d7-877e-bcfb837db215",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting pyearth\n",
      "  Using cached pyearth-0.1.23-py2.py3-none-any.whl.metadata (6.1 kB)\n",
      "Requirement already satisfied: numpy in /opt/conda/lib/python3.10/site-packages (from pyearth) (1.24.4)\n",
      "Collecting gdal (from pyearth)\n",
      "  Using cached GDAL-3.8.3.tar.gz (802 kB)\n",
      "  Preparing metadata (setup.py) ... \u001b[?25lerror\n",
      "  \u001b[1;31merror\u001b[0m: \u001b[1msubprocess-exited-with-error\u001b[0m\n",
      "  \n",
      "  \u001b[31m×\u001b[0m \u001b[32mpython setup.py egg_info\u001b[0m did not run successfully.\n",
      "  \u001b[31m│\u001b[0m exit code: \u001b[1;36m1\u001b[0m\n",
      "  \u001b[31m╰─>\u001b[0m \u001b[31m[85 lines of output]\u001b[0m\n",
      "  \u001b[31m   \u001b[0m running egg_info\n",
      "  \u001b[31m   \u001b[0m creating /tmp/pip-pip-egg-info-naaw9it0/GDAL.egg-info\n",
      "  \u001b[31m   \u001b[0m writing /tmp/pip-pip-egg-info-naaw9it0/GDAL.egg-info/PKG-INFO\n",
      "  \u001b[31m   \u001b[0m writing dependency_links to /tmp/pip-pip-egg-info-naaw9it0/GDAL.egg-info/dependency_links.txt\n",
      "  \u001b[31m   \u001b[0m writing requirements to /tmp/pip-pip-egg-info-naaw9it0/GDAL.egg-info/requires.txt\n",
      "  \u001b[31m   \u001b[0m writing top-level names to /tmp/pip-pip-egg-info-naaw9it0/GDAL.egg-info/top_level.txt\n",
      "  \u001b[31m   \u001b[0m writing manifest file '/tmp/pip-pip-egg-info-naaw9it0/GDAL.egg-info/SOURCES.txt'\n",
      "  \u001b[31m   \u001b[0m Traceback (most recent call last):\n",
      "  \u001b[31m   \u001b[0m   File \"/tmp/pip-install-pmq6n8t8/gdal_570d8a58329d4646a6ba5867d0567c99/setup.py\", line 89, in fetch_config\n",
      "  \u001b[31m   \u001b[0m     p = subprocess.Popen([command, args], stdout=subprocess.PIPE)\n",
      "  \u001b[31m   \u001b[0m   File \"/opt/conda/lib/python3.10/subprocess.py\", line 971, in __init__\n",
      "  \u001b[31m   \u001b[0m     self._execute_child(args, executable, preexec_fn, close_fds,\n",
      "  \u001b[31m   \u001b[0m   File \"/opt/conda/lib/python3.10/subprocess.py\", line 1847, in _execute_child\n",
      "  \u001b[31m   \u001b[0m     raise child_exception_type(errno_num, err_msg, err_filename)\n",
      "  \u001b[31m   \u001b[0m FileNotFoundError: [Errno 2] No such file or directory: 'gdal-config'\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m During handling of the above exception, another exception occurred:\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m Traceback (most recent call last):\n",
      "  \u001b[31m   \u001b[0m   File \"/tmp/pip-install-pmq6n8t8/gdal_570d8a58329d4646a6ba5867d0567c99/setup.py\", line 190, in get_gdal_config\n",
      "  \u001b[31m   \u001b[0m     return fetch_config(option, gdal_config=self.gdal_config)\n",
      "  \u001b[31m   \u001b[0m   File \"/tmp/pip-install-pmq6n8t8/gdal_570d8a58329d4646a6ba5867d0567c99/setup.py\", line 92, in fetch_config\n",
      "  \u001b[31m   \u001b[0m     raise gdal_config_error(e)\n",
      "  \u001b[31m   \u001b[0m __main__.gdal_config_error: [Errno 2] No such file or directory: 'gdal-config'\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m During handling of the above exception, another exception occurred:\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m Traceback (most recent call last):\n",
      "  \u001b[31m   \u001b[0m   File \"<string>\", line 2, in <module>\n",
      "  \u001b[31m   \u001b[0m   File \"<pip-setuptools-caller>\", line 34, in <module>\n",
      "  \u001b[31m   \u001b[0m   File \"/tmp/pip-install-pmq6n8t8/gdal_570d8a58329d4646a6ba5867d0567c99/setup.py\", line 360, in <module>\n",
      "  \u001b[31m   \u001b[0m     setup(\n",
      "  \u001b[31m   \u001b[0m   File \"/opt/conda/lib/python3.10/site-packages/setuptools/__init__.py\", line 87, in setup\n",
      "  \u001b[31m   \u001b[0m     return distutils.core.setup(**attrs)\n",
      "  \u001b[31m   \u001b[0m   File \"/opt/conda/lib/python3.10/site-packages/setuptools/_distutils/core.py\", line 185, in setup\n",
      "  \u001b[31m   \u001b[0m     return run_commands(dist)\n",
      "  \u001b[31m   \u001b[0m   File \"/opt/conda/lib/python3.10/site-packages/setuptools/_distutils/core.py\", line 201, in run_commands\n",
      "  \u001b[31m   \u001b[0m     dist.run_commands()\n",
      "  \u001b[31m   \u001b[0m   File \"/opt/conda/lib/python3.10/site-packages/setuptools/_distutils/dist.py\", line 968, in run_commands\n",
      "  \u001b[31m   \u001b[0m     self.run_command(cmd)\n",
      "  \u001b[31m   \u001b[0m   File \"/opt/conda/lib/python3.10/site-packages/setuptools/dist.py\", line 1217, in run_command\n",
      "  \u001b[31m   \u001b[0m     super().run_command(command)\n",
      "  \u001b[31m   \u001b[0m   File \"/opt/conda/lib/python3.10/site-packages/setuptools/_distutils/dist.py\", line 987, in run_command\n",
      "  \u001b[31m   \u001b[0m     cmd_obj.run()\n",
      "  \u001b[31m   \u001b[0m   File \"/opt/conda/lib/python3.10/site-packages/setuptools/command/egg_info.py\", line 308, in run\n",
      "  \u001b[31m   \u001b[0m     self.find_sources()\n",
      "  \u001b[31m   \u001b[0m   File \"/opt/conda/lib/python3.10/site-packages/setuptools/command/egg_info.py\", line 316, in find_sources\n",
      "  \u001b[31m   \u001b[0m     mm.run()\n",
      "  \u001b[31m   \u001b[0m   File \"/opt/conda/lib/python3.10/site-packages/setuptools/command/egg_info.py\", line 560, in run\n",
      "  \u001b[31m   \u001b[0m     self.add_defaults()\n",
      "  \u001b[31m   \u001b[0m   File \"/opt/conda/lib/python3.10/site-packages/setuptools/command/egg_info.py\", line 597, in add_defaults\n",
      "  \u001b[31m   \u001b[0m     sdist.add_defaults(self)\n",
      "  \u001b[31m   \u001b[0m   File \"/opt/conda/lib/python3.10/site-packages/setuptools/command/sdist.py\", line 106, in add_defaults\n",
      "  \u001b[31m   \u001b[0m     super().add_defaults()\n",
      "  \u001b[31m   \u001b[0m   File \"/opt/conda/lib/python3.10/site-packages/setuptools/_distutils/command/sdist.py\", line 252, in add_defaults\n",
      "  \u001b[31m   \u001b[0m     self._add_defaults_ext()\n",
      "  \u001b[31m   \u001b[0m   File \"/opt/conda/lib/python3.10/site-packages/setuptools/_distutils/command/sdist.py\", line 336, in _add_defaults_ext\n",
      "  \u001b[31m   \u001b[0m     build_ext = self.get_finalized_command('build_ext')\n",
      "  \u001b[31m   \u001b[0m   File \"/opt/conda/lib/python3.10/site-packages/setuptools/_distutils/cmd.py\", line 306, in get_finalized_command\n",
      "  \u001b[31m   \u001b[0m     cmd_obj.ensure_finalized()\n",
      "  \u001b[31m   \u001b[0m   File \"/opt/conda/lib/python3.10/site-packages/setuptools/_distutils/cmd.py\", line 109, in ensure_finalized\n",
      "  \u001b[31m   \u001b[0m     self.finalize_options()\n",
      "  \u001b[31m   \u001b[0m   File \"/tmp/pip-install-pmq6n8t8/gdal_570d8a58329d4646a6ba5867d0567c99/setup.py\", line 266, in finalize_options\n",
      "  \u001b[31m   \u001b[0m     gdaldir = self.get_gdal_config('prefix')\n",
      "  \u001b[31m   \u001b[0m   File \"/tmp/pip-install-pmq6n8t8/gdal_570d8a58329d4646a6ba5867d0567c99/setup.py\", line 196, in get_gdal_config\n",
      "  \u001b[31m   \u001b[0m     raise gdal_config_error(traceback_string + '\\n' + msg)\n",
      "  \u001b[31m   \u001b[0m __main__.gdal_config_error: Traceback (most recent call last):\n",
      "  \u001b[31m   \u001b[0m   File \"/tmp/pip-install-pmq6n8t8/gdal_570d8a58329d4646a6ba5867d0567c99/setup.py\", line 89, in fetch_config\n",
      "  \u001b[31m   \u001b[0m     p = subprocess.Popen([command, args], stdout=subprocess.PIPE)\n",
      "  \u001b[31m   \u001b[0m   File \"/opt/conda/lib/python3.10/subprocess.py\", line 971, in __init__\n",
      "  \u001b[31m   \u001b[0m     self._execute_child(args, executable, preexec_fn, close_fds,\n",
      "  \u001b[31m   \u001b[0m   File \"/opt/conda/lib/python3.10/subprocess.py\", line 1847, in _execute_child\n",
      "  \u001b[31m   \u001b[0m     raise child_exception_type(errno_num, err_msg, err_filename)\n",
      "  \u001b[31m   \u001b[0m FileNotFoundError: [Errno 2] No such file or directory: 'gdal-config'\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m During handling of the above exception, another exception occurred:\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m Traceback (most recent call last):\n",
      "  \u001b[31m   \u001b[0m   File \"/tmp/pip-install-pmq6n8t8/gdal_570d8a58329d4646a6ba5867d0567c99/setup.py\", line 190, in get_gdal_config\n",
      "  \u001b[31m   \u001b[0m     return fetch_config(option, gdal_config=self.gdal_config)\n",
      "  \u001b[31m   \u001b[0m   File \"/tmp/pip-install-pmq6n8t8/gdal_570d8a58329d4646a6ba5867d0567c99/setup.py\", line 92, in fetch_config\n",
      "  \u001b[31m   \u001b[0m     raise gdal_config_error(e)\n",
      "  \u001b[31m   \u001b[0m gdal_config_error: [Errno 2] No such file or directory: 'gdal-config'\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m Could not find gdal-config. Make sure you have installed the GDAL native library and development headers.\n",
      "  \u001b[31m   \u001b[0m \u001b[31m[end of output]\u001b[0m\n",
      "  \n",
      "  \u001b[1;35mnote\u001b[0m: This error originates from a subprocess, and is likely not a problem with pip.\n",
      "\u001b[1;31merror\u001b[0m: \u001b[1mmetadata-generation-failed\u001b[0m\n",
      "\n",
      "\u001b[31m×\u001b[0m Encountered error while generating package metadata.\n",
      "\u001b[31m╰─>\u001b[0m See above for output.\n",
      "\n",
      "\u001b[1;35mnote\u001b[0m: This is an issue with the package mentioned above, not pip.\n",
      "\u001b[1;36mhint\u001b[0m: See above for details.\n",
      "\u001b[?25hNote: you may need to restart the kernel to use updated packages.\n"
     ]
    }
   ],
   "source": [
    "pip install pyearth"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "id": "4b505124-62a3-4fa1-98fb-11fc3a444969",
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import numpy as np\n",
    "from sklearn.model_selection import LeaveOneOut\n",
    "from sklearn.ensemble import RandomForestRegressor\n",
    "from sklearn.metrics import mean_squared_error\n",
    "import ast\n",
    "from xgboost import XGBRegressor\n",
    "from sklearn.svm import SVR\n",
    "from sklearn.tree import DecisionTreeRegressor\n",
    "#from pyearth import Earth\n",
    "\n",
    "ela_data = pd.read_csv('New_Transformed_File.csv')\n",
    "ert_data = pd.read_csv('rel_ERT.csv')\n",
    "\n",
    "merged_data = pd.merge(ela_data, ert_data, on=['fid', 'dim'])\n",
    "target_columns = [\"BSqi\", \"BSrr\", \"CMA-CSA\", \"fmincon\", \"fminunc\", \"HCMA\",\n",
    "                  \"HMLSL\", \"IPOP400D\", \"MCS\", \"MLSL\", \"OQNLP\", \"SMAC-BBOB\"]\n",
    "\n",
    "def safe_eval(x):\n",
    "    try:\n",
    "        return ast.literal_eval(x)\n",
    "    except (SyntaxError, ValueError):\n",
    "        return None\n",
    "\n",
    "merged_data['features'] = merged_data['features'].apply(safe_eval)\n",
    "\n",
    "merged_data = merged_data.dropna(subset=['features'])\n",
    "max_len = merged_data['features'].apply(len).max()  # Find the maximum length of lists\n",
    "#merged_data['features'] = merged_data['features'].apply(lambda x: x + [0] * (max_len - len(x)) if x is not None else [0] * max_len)\n",
    "\n",
    "rf_model = RandomForestRegressor(n_estimators=500, random_state=42,max_features=int(max_len/3))\n",
    "svm_model = SVR(kernel='rbf')\n",
    "model_xgboost = XGBRegressor(objective='rank:pairwise', random_state=42)\n",
    "dt_model = DecisionTreeRegressor()\n",
    "#mars_model = Earth()\n",
    "\n",
    "loo = LeaveOneOut()\n",
    "mse_dict = {}\n",
    "result_data = pd.DataFrame(columns=['mbse for RandomForest', 'mbse for xgboost','mbse for SVM','mbse for RPart','Algorithm'])\n",
    "for target_column in target_columns:\n",
    "    mse_dict[target_column] = {}\n",
    "    # Extract features (X) and target variable (y)\n",
    "    X = np.array(merged_data['features'].tolist())\n",
    "    y = np.array(merged_data[target_column].tolist())\n",
    "    \n",
    "    mse_list = []\n",
    "    mse_xgboost_list = []\n",
    "    mse_svm_list = []\n",
    "    mse_dt_list = []\n",
    "    mse_mars_list = []\n",
    "    for train_index, test_index in loo.split(merged_data):\n",
    "        X_train, X_test = X[train_index], X[test_index]\n",
    "        y_train, y_test = y[train_index], y[test_index]\n",
    "                   \n",
    "                \n",
    "        rf_model.fit(X_train, y_train)\n",
    "        y_pred = rf_model.predict(X_test)\n",
    "        mse = mean_squared_error(y_test, y_pred)\n",
    "        mse_list.append(mse)\n",
    "                    \n",
    "        model_xgboost.fit(X_train, y_train)\n",
    "        y_pred_xgboost = model_xgboost.predict(X_train)\n",
    "        mbse_xgboost = mean_squared_error(y_train, y_pred_xgboost)\n",
    "        mse_xgboost_list.append(mbse_xgboost)\n",
    "                    \n",
    "        svm_model.fit(X_train, y_train)\n",
    "        y_pred_svm = model_xgboost.predict(X_train)\n",
    "        mbse_svm = mean_squared_error(y_train, y_pred_svm)\n",
    "        mse_svm_list.append(mbse_svm)\n",
    "                    \n",
    "        dt_model.fit(X_train, y_train)\n",
    "        y_pred_dt = dt_model.predict(X_train)\n",
    "        mbse_dt = mean_squared_error(y_train, y_pred_dt)\n",
    "        mse_dt_list.append(mbse_dt)\n",
    "        \n",
    "        #mars_model.fit(X_train, y_train)\n",
    "        #y_pred_mars = dt_model.predict(X_train)\n",
    "        #mbse_mars = mean_squared_error(y_train, y_pred_mars)\n",
    "        #mse_mars_list.append(mbse_mars)\n",
    "                    \n",
    "    avg_mse = np.mean(mse_list)\n",
    "    avg_mse_xgboost = np.mean(mse_xgboost_list)\n",
    "    avg_mse_svm = np.mean(mse_svm_list)\n",
    "    avg_mse_dt = np.mean(mse_dt_list)\n",
    "    #avg_mse_mars = np.mean(mse_mars_list)\n",
    "\n",
    "    result_data = pd.concat([result_data, pd.DataFrame({'mbse for RandomForest': [avg_mse],'mbse for xgboost': [avg_mse_xgboost],'mbse for SVM': [avg_mse_svm],'mbse for RPart': [avg_mse_dt],'Algorithm': [target_column]})], ignore_index=True)\n",
    "\n",
    "\n",
    "result_data.to_csv(\"mbse_data_New.csv\", encoding='utf-8', index=False)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "6d3a2e35-58fe-4709-af42-3e434221a93f",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
